# Site settings
title: John Dulin
email: dulinjd@gmail.com
description: "John Dulin.  Hacking.  Physics.  Robots."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
