# Site settings
title: John Dulin
email: dulinjd@gmail.com
description: "John Dulin.  Hacking.  Physics.  Robots. Theater."
baseurl: ""
url: "http://johndulin.com"

pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Resume: '/resume/'

# Build settings
markdown: kramdown
permalink: pretty
